FROM python:3.12-slim AS base
ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1


WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

FROM base AS runtime
COPY . .

ENV S3_BUCKET="{{ lfk_s3_bucket_name }}"

EXPOSE 5000
CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]
