---
# tasks file for lfk.s3_frontend
- name: spawn ec2 instance
  amazon.aws.ec2_instance:
    name: "public_s3_frontend"
    instance_type: "{{ lfk_aws_instance_type | default('t3.medium') }}"
    image_id: "{{ lfk_aws_ami }}"
    security_group: default
    key_name: "ansible"
    region: "{{ lfk_aws_region | default('eu-north-1') }}"
    access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"

- name: create S3 bucket for the app
  amazon.aws.s3_bucket:
    name: "{{ lfk_aws_bucket_name }}"
    state: present
    region: "eu-north-1"
